fix: graph timeframe updates after website idle
galacticcouncil/Basilisk-ui-old pull request #182
Opened 2022-04-07 16:01 UTC by Matehoo

## Description
Refetches dataset after last data point is older than 1 minute.
Added `react-page-visibility` for stopping refetching new data if the tab is not visible.

## Related Issue
Fixes: #155

2022-04-11 11:49 UTC, maht0rz commented on src/pages/TradePage/TradePage.tsx
> +        !datasetRefreshing &&
this would also prevent the from/to from being updated, while the query is already in flight. I don't think this is 100% desired behavior, is it?

2022-04-11 11:49 UTC, maht0rz commented on src/pages/TradePage/TradePage.tsx
> +          dataset?.[dataset?.length - 1]?.x <= new Date().getTime() - lastRecordOutdatedBy)
lodash -> `last()`

2022-04-11 11:50 UTC, maht0rz commented on src/pages/TradePage/TradePage.tsx
> +        !datasetRefreshing &&
also please use `networkStatus` here

2022-04-11 11:52 UTC, maht0rz requested changes
Please address the comments before we can proceed to QA/testing.

2022-04-13 19:43 UTC, mckrava commented
:page_with_curl: **Basilisk UI reporter** <br /> _Report has been triggered by commit [fix: use lodash and add guard clause for refreshing (a8df783edd336775eb5e4ae60517b37b87bd9e71)](https://github.com/galacticcouncil/Basilisk-ui/commit/a8df783edd336775eb5e4ae60517b37b87bd9e71)_ <hr />:small_blue_diamond: **App/Storybook build:** <br />    - Status: :white_check_mark: _Built_ <hr />:small_blue_diamond: **App/Storybook deployment:** <br />    - Status: :white_check_mark: _Deployed_     <br />    - [Application build page](https://basilisk-testnet.hydration.cloud/fix/155-graph-doesnt-update-to-the-appropriate-timeframe-once-the-website-has-been-idle/app) <br />    - [Storybook build page](https://basilisk-testnet.hydration.cloud/fix/155-graph-doesnt-update-to-the-appropriate-timeframe-once-the-website-has-been-idle/storybook)

2022-04-26 11:42 UTC, maht0rz approved these changes
lgtm

2022-04-26 11:44 UTC, merged