feat/ci_testing_storybook_stories
galacticcouncil/Basilisk-ui-old pull request #93
Opened 2022-02-02 13:30 UTC by timothydm42

## Description
Presentation layer testing functionality and docs

## Motivation and Context
Dev experience and integrity of our UIs

## How Has This Been Tested?
This _is_ testing... 👻

## Checklist:
- [x] I have updated the documentation if necessary.
- [x] I have added tests to cover my changes, regression test if fixing an issue.
- [ ] This is a breaking change.
- [x] storybook testing config
- [x] Docs on Presentation layer testing 
- [x] scripts for storybook/presentation layer deving
- [x] CI script to test storybook/presentation layer
- [x] GH action

2022-02-03 12:05 UTC, maht0rz requested changes

2022-02-03 12:05 UTC, maht0rz commented on README.md
> +### Storybook testing
y not make this part of the presentational layer testing above?

also when i run `yarn storybook:test` i get `zsh:1: permission denied: src/components/Button/Button.stories.test.ts` after the tests run successfully.

2022-02-03 12:05 UTC, maht0rz commented on README.md
> +### Storybook testing
Is it possible to combine `watch` and `headed`? it didnt work when  tried with `yarn storybook:test:watch --headed`

2022-02-03 12:05 UTC, maht0rz commented on README.md
> +```shell
shall we add this to `yarn start` directly? or the `.env` config or somewhere where it auto runs since we're all on node v17 now?

2022-02-03 12:05 UTC, maht0rz commented on craco.config.js
> +      webpackConfig.resolve.fallback = {
what does this fix?

2022-02-03 12:05 UTC, maht0rz commented on package.json
> +    "test": "craco test --transformIgnorePatterns 'node_modules/(?!@polkadot)/' --testPathIgnorePatterns './*\\.stories.test\\.ts$'",
y not put this into `jest.config.js`?

2022-02-03 12:05 UTC, maht0rz commented on package.json
> +    "storybook:test:watch": "yarn chokidar \"src/**/*.{ts*,scss}\" -c 'yarn storybook:test --retries=0 && {path}'",
i'd watch everything in `src/` not just ts/scss files, you might import a JSON file and then this would not work well

2022-02-03 12:05 UTC, maht0rz commented on package.json
> +    "storybook:test:watch": "yarn chokidar \"src/**/*.{ts*,scss}\" -c 'yarn storybook:test --retries=0 && {path}'",
or even an svg or another kinds of assets

2022-02-03 12:05 UTC, maht0rz commented on package.json
> +    "storybook:test": "npx playwright test --config=storybook-testing/playwright.config.ts",
lets use the locally installed version, not npx

2022-02-03 12:05 UTC, maht0rz commented on package.json
>      "build-storybook": "build-storybook",
this should be prefixed as `storybook:build` and the CI needs to be updated then too

2022-02-03 12:06 UTC, maht0rz requested changes

2022-02-03 12:06 UTC, maht0rz commented on storybook-testing/teardown.ts
> +async function makeReport() {
we now have like 3 teardown files for different tests, maybe some portions of the teardown scripts could be shared?

2022-02-03 12:22 UTC, timothydm42 commented
Links that might help understand how TS works with Storybook and what we want to configure,  if anything:

- https://github.com/storybookjs/storybook/issues/9666
- https://storybook.js.org/docs/react/configure/typescript

ok I'm out 🙇

2022-02-10 08:39 UTC, mckrava approved these changes

2022-02-10 08:39 UTC, mckrava commented on README.md
> +```shell
I've added this var to `.env` and to `start`, `build` commands but I think it's temporary. It should be removed in future.

2022-02-10 08:39 UTC, mckrava commented on craco.config.js
> +      webpackConfig.resolve.fallback = {
It fixes browser polyfills - https://github.com/digitalbazaar/forge/issues/908#issuecomment-914188644
It's because we migrated to webpack5.

2022-02-10 08:39 UTC, mckrava commented on package.json
> +    "test": "craco test --transformIgnorePatterns 'node_modules/(?!@polkadot)/' --testPathIgnorePatterns './*\\.stories.test\\.ts$'",
Already moved.

2022-02-10 08:39 UTC, mckrava commented on package.json
> +    "storybook:test": "npx playwright test --config=storybook-testing/playwright.config.ts",
Moved playwright runs from npx to yarn.

2022-02-10 08:39 UTC, mckrava commented on package.json
> +    "storybook:test:watch": "yarn chokidar \"src/**/*.{ts*,scss}\" -c 'yarn storybook:test --retries=0 && {path}'",
Fixed.

2022-02-10 08:39 UTC, mckrava commented on package.json
>      "build-storybook": "build-storybook",
Done.

2022-02-10 08:39 UTC, mckrava commented on storybook-testing/teardown.ts
> +async function makeReport() {
I've added one global teardown file for all tests. It's not the best one, but it's only what I found. Problem is that parameter `globalTeardown` in Playwright and jest configs - it's a string - path to file with teardown function, this parameter doesn't receive function itself. It means that I cannot pass some parameter directly to teardown function for identifying what test runner is an executor of the function. So I've found that current solution is most stable. Drawback - all 3 `.xml` result files will be converted after running of at least one test-runner (unit | e2e | storybook).

2022-02-10 08:39 UTC, mckrava commented on README.md
> +### Storybook testing
I didn't find solution for watch mode with `--headed` flag. Possible reason - tests are running with `chokidar`. 
So I've added separate command - `yarn storybook:test:watch-headed`.

`zsh:1: permission denied` has been fixed.

2022-02-11 13:22 UTC, maht0rz approved these changes

2022-02-11 13:22 UTC, merged